#Test Data/Locators should not be written in Config file
#Config/Environment Properties should be written here

browser=chrome
url= https://www.google.com

username=reshmi@gmail.com
password=reshmi@123

headless=true
#incognito=true